"""temporal.types implementation."""

from __future__ import annotations

from enum import Enum


class EvidenceStatus(str, Enum):
    AVAILABLE = "AVAILABLE"
    UNKNOWN = "UNKNOWN"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    INVALID = "INVALID"
    NOT_AUTHORIZED = "NOT_AUTHORIZED"


class OpportunityWindowStatus(str, Enum):
    WINDOW_OBSERVED = "WINDOW_OBSERVED"
    NO_WINDOW_EVIDENCE_TOO_LATE = "NO_WINDOW_EVIDENCE_TOO_LATE"
    NO_WINDOW_EVIDENCE_NEVER_SUFFICIENT = (
        "NO_WINDOW_EVIDENCE_NEVER_SUFFICIENT"
    )
    RIGHT_CENSORED = "RIGHT_CENSORED"
    COMMITMENT_NOT_REACHED = "COMMITMENT_NOT_REACHED"
    INVALID_ENGINEERING_EVIDENCE = "INVALID_ENGINEERING_EVIDENCE"


class QueryNecessityGold(str, Enum):
    QUERY_NECESSARY = "QUERY_NECESSARY"
    QUERY_NOT_NECESSARY = "QUERY_NOT_NECESSARY"
    GOLD_UNKNOWN = "GOLD_UNKNOWN"


EVIDENCE_FIELD_IDS = (
    "E1_INTERPRETATION_VALIDITY",
    "E2_GROUNDING",
    "E3_CURRENT_ACTION_RELATION",
    "E4_FUTURE_OBLIGATION_RELATION",
    "E5_ROUTE_LANE_TOPOLOGY_RELATION",
    "E6_CANDIDATE_CONSEQUENCE_DIVERGENCE",
    "E7_SAFETY_RULE_HOLDING",
    "E8_RECOVERABILITY",
    "E9_ANSWER_CHANGES_ACTION",
)


__all__ = [
    "EVIDENCE_FIELD_IDS",
    "EvidenceStatus",
    "OpportunityWindowStatus",
    "QueryNecessityGold",
]
