"""候选/契约/代码冻结；本文件从不生成种子或运行模型。"""
import sys
from common import *
sys.path.insert(0,str(ROOT))
from driveclarify_language_grounding_v1.slot_parser import SemanticSlotParser
from driveclarify_rq1_v2.consequence import TaskSignature,compare_task_signatures

def main():
 assert not (R/'V3_CANDIDATE_POOL_FREEZE_RECEIPT.json').exists()
 pool=read(R/'V3_HOST_CANDIDATE_POOL.json');scene=read(R/'geometry/NATIVE_SCENE_QUALIFICATION.json');tests=read(R/'geometry/TASK_EVALUATOR_VALIDATION.json')
 assert scene['pass'] and tests['pass'] and len(pool['templates'])==14
 checks=[]
 for t in pool['templates']:
  expected={'REF':'REFERENTIAL','LMK':'LANDMARK','ORD':'SPATIAL_ORDER','USC':'UNDERSPECIFIED_CONSTRAINT'}[t['family']]
  parsed=SemanticSlotParser().parse(t['instruction']).to_dict();assert parsed['ambiguity_kind']==expected,(t['template_id'],parsed)
  b=read(t['task_binding_path']);signatures=[TaskSignature.from_mapping({'candidate_id':k,'certified':True,'certificate_id':t['template_id']+'-'+k,'relevant_components':['task_completion_region'],'task_completion_region':b['candidate_zone_map'][k]}) for k in ['1','2']]
  relation=compare_task_signatures(*signatures).relation.value;assert relation==t['task_relation']
  n=t['route_neutrality'];assert n['route_context_digest_interpretation1']==n['route_context_digest_interpretation2']
  checks.append({'template_id':t['template_id'],'parsed':parsed,'task_relation':relation,'route_neutrality':'PASS','A0_interface':'PASS','arm_independent_evaluator':'PASS','source_map_lane_legality':'PASS','native_public_scene_geometry':'PASS','task_evaluator_validity':'PASS'})
 write(R/'geometry/SEMANTIC_AND_BINDING_CHECKS.json',{'checks':checks,'pass':True,'scope':'PRE_PERFORMANCE_CONTRACT_AND_NATIVE_SCENE_CHECKS'})
 contract={'stage':pool['stage'],'scope':'DEVELOPMENT_ONLY_TASK_HOST_EXECUTABILITY_CERTIFICATION','arm':'A_STAR','arm_display':'A*','backbone_checkpoint':str(CHECKPOINT),'checkpoint_sha256':CHECKPOINT_SHA,'native_raw_language_interface':str(ROOT/'driveclarify_rq3_paired_v2/a0_agent.py'),'interface_reuse_does_not_make_this_A0_formal_arm':True,'only_language_task_disambiguated':True,'DriveClarify':False,'ASK':False,'oracle_control':False,'special_trajectory':False,'same_official_route_targets_destination':True,'same_native_PID_controller':True,'evaluator':str(R/'tooling/task_evaluator.py'),'endpoint':'explicit local task completed AND native completion AND no inherited major safety failure','native_completion':'official status Perfect/Completed OR Route Completion >=95','major_safety_event_union':['collisions_layout','collisions_vehicle','collisions_pedestrian','outside_route_lanes','route_dev'],'diagnostic_only':['Driving_Score','Route_Completion'],'per_tested_template_runs':6,'interpretation1_fresh_seeds':3,'interpretation2_fresh_seeds':3,'pass_threshold_per_interpretation':'2/3','all_six_authoritatively_evaluable_required':True,'additional_gates':['task evaluator validity PASS','route neutrality PASS','no true-intent/route leak','source/checkpoint/controller integrity PASS'],'family_order':FAMILIES,'candidate_order':['P1','P2'],'P2_executed_only_if_P1_fails':True,'stop_formal_authorization_if_any_family_fails':True,'continue_other_families_for_complete_qualification_evidence':True,'P3':False,'valid_failures':['collision','wrong local task','timeout','blocked','noncompletion','no entry into certified task region','low Driving Score'],'valid_failure_retry':False,'development_seed_replacement':False,'technical_invalidity':'genuine missing/corrupt authoritative evidence or infrastructure failure; retained UNKNOWN, no replacement in this stage','native_entry_retries':'inherited launcher pre-world/pre-evaluator startup retries only; no native exposure retry','seeds_generated_after_pool_freeze':True,'development_seeds_permanently_excluded_from_future_formal':True,'seed_semantics':'unchanged native --traffic-manager-seed; no new model RNG seeding or deterministic algorithm settings','native_evaluator_timeout_s':480,'wall_watchdog_s':7200,'formal_ambiguous_seeds_authorized':False,'formal_ambiguous_runs_authorized':False,'superiority_analysis_freeze_authorized':False,'created_utc':now()}
 write(R/'A_STAR_SCIENTIFIC_QUALIFICATION_CONTRACT.json',contract)
 (R/'A_STAR_SCIENTIFIC_QUALIFICATION_CONTRACT.md').write_text('# A* 开发资格契约\n\nA* 是冻结 SimLingo + 明确无歧义任务，仅作宿主可执行性资格，不是方法 baseline，也不与历史 A0/A1 统计比较。复用冻结原文语言接口；不调用 DriveClarify、ASK、oracle、路线安装或特殊轨迹。仅语言说明改变，官方 XML、目标点、终点、checkpoint、模型 forward、PID/控制器相同。\n\n每个实际测试模板 6 个独立开发 seed：解释1三次、解释2三次。六次均须权威可评估，每个解释 TCSC≥2/3，评估器有效性/路线中立/无泄漏/源完整性均 PASS，才通过。TCSC = 正确完成局部任务 ∧ 原生完成 ∧ 无历史重大安全失败；原生完成与重大安全集合严格复用 V2 official_metrics.py。DS/RC 是诊断，不能独自授予资格。\n\n每族固定 P1→P2。P1 通过不运行 P2；P1 失败保留失败再测试 P2；两者失败终止未来正式授权，但继续完成其他族资格证据。种子只在本池冻结之后生成，永久排除未来正式实验。有效失败不重试、不换种子；基础设施缺失记 UNKNOWN，本阶段同样不重新暴露。USC-E/P3/正式歧义 A0/A1/正式种子/最终优效冻结全部禁止。\n')
 (R/'V3_TASK_EVALUATOR_SPEC.md').write_text('# 局部变道任务评估器\n\n版本 V3_FIRST_ADJACENT_LANE_ENTRY_1。输入仅为完整原生状态轨迹、冻结地图绑定、原生终端收据及官方时长，不读取 A1 变量。先复用历史完整轨迹证据包校验：SHA256、连续 world frames、单调时钟、无观察器错误、全车8顶点、覆盖官方时长；不足为 UNKNOWN。\n\n初始必须位于 road67/lane−2。找首次 ego 中心进入 lane−1 的事件，以地图投影确定纵向位置。首次进入须在指定锥桶区间；随后完整车身在同一区间且完全处于邻道内连续≥0.25s，朝向差≤20°、roll/pitch≤20°。返回原车道后再次进入不能替代第一次。区间外变道、未完整入区、没有变道、停滞和超时在完整证据下均为任务未完成。\n\nHIGH 两个区间互不重叠，解释1/2要求不同区间；LOW 两个解释映射同一区间。先提取 completed_zone，再独立同时评分两个解释。端点不读取控制指令或选中 candidate。全程观测收据缺失不可当成科学零。146 项合成软件检查只验证评分逻辑，不算原生资格或政策性能。\n')
 (R/'V3_ROUTE_NEUTRALITY_AUDIT.md').write_text('# 路线中立性\n\n14/14 静态 PASS。同一个原始 bench2drive_167.xml 用于所有解释及未来 A0/A1/A* 接口，官方 route、目标点、终点均无解释选择参数。HIGH 两个局部变道区间都偏离同一原车道且均可回到同一终点，官方路线不编码哪个时机是真意；LOW 两种语言共享同一后果。公开两候选标记同时存在。\n\npool 对每个模板保存解释互换时相同的公共路线投影 SHA256；A* 只通过授权的明确语言拿到解释，不能从 evaluator JSON 或地图候选几何控制车辆。该投影证明无真意注入，不证明原生模型对两解释没有偏好；偏好由两解释各三次资格检验约束。\n\n14 个原生静态场景已检查公开实体完整包围盒不占行车道；雨雾保持官方条件，图像显示近远参照及地标存在。P1/P2 的改动均在模型性能暴露前冻结。初选 Town04 因护栏实体放置失败放弃，未运行模型。\n')
 (R/'V3_TASK_BINDING_CERTIFICATION.md').write_text('# 任务绑定资格\n\n14/14 在策略运行前通过地图合法性、公开实体放置、确定性软件评估器及 frozen family parser/RQ1 task-signature 后果检查。REF 是白色车辆指称，LMK 是两个固定 kiosk 建筑式地标，ORD 是全部锥桶对与带路肩告示牌的锥桶对计数域，USC 是距离区间欠定。HIGH 后果 TASK_CRITICAL，LOW TASK_EQUIVALENT。\n\n静态场景照片不是人类独立标注，也不是驾驶可执行性证据。雨雾可见性和语言执行难度必须保留为资格挑战，不能因此更换已暴露模板。原生应急车辆场景及天气完整保留。两种明确语言使用同一局部任务 evaluator；行为端点不是官方终点。\n\n详见 geometry/NATIVE_SCENE_QUALIFICATION.json、geometry/SEMANTIC_AND_BINDING_CHECKS.json 和 geometry/TASK_EVALUATOR_VALIDATION.json。\n')
 manifest=read(ROOT/'reports/driveclarify_rq3_paired_comparison_v2_task_binding_qualification_and_execution/formal/FREEZE_MANIFEST.json')
 runtime={r['path']:r for r in manifest['runtime_files']}
 for row in runtime.values():assert sha(row['path'])==row['sha256'],row['path']
 for p in (R/'tooling').iterdir():
  if p.is_file() and p.suffix in ['.py','.sh']:runtime[str(p)]={'path':str(p),'sha256':sha(p)}
 inputs=[R/'V3_HOST_CANDIDATE_POOL.json',R/'A_STAR_SCIENTIFIC_QUALIFICATION_CONTRACT.json',R/'V3_TASK_EVALUATOR_SPEC.md',R/'V3_ROUTE_NEUTRALITY_AUDIT.md',R/'V3_TASK_BINDING_CERTIFICATION.md']+list((R/'candidate_assets').rglob('*.json'))+list((R/'geometry').glob('*.json'))
 frozen={'created_utc':now(),'runtime_files':list(runtime.values()),'input_files':[{'path':str(p),'sha256':sha(p)} for p in inputs]}
 write(R/'audit/QUALIFICATION_FREEZE_MANIFEST.json',frozen)
 receipt={'stage':pool['stage'],'status':'CANDIDATE_POOL_AND_A_STAR_CONTRACT_FROZEN','sealed_utc':now(),'freeze_digest':sha(R/'audit/QUALIFICATION_FREEZE_MANIFEST.json'),'candidate_pool_sha256':sha(R/'V3_HOST_CANDIDATE_POOL.json'),'total_candidate_templates_frozen':14,'native_policy_runs_at_freeze':0,'development_seeds_generated_at_freeze':0,'formal_ambiguous_seeds_generated':0,'formal_ambiguous_native_runs':0,'source_entry_reverification':read(R/'audit/ENTRY_REVERIFICATION.json'),'candidate_order':['P1','P2'],'pass_rule':'all6 evaluable + both >=2/3 + all static/integrity gates PASS','future_formal_analysis_freeze':False}
 write(R/'V3_CANDIDATE_POOL_FREEZE_RECEIPT.json',receipt);print(receipt['freeze_digest'])
if __name__=='__main__':main()
